-- migrate:up 

INSERT INTO nations (id, name) VALUES (1, 'Albania');
INSERT INTO nations (id, name) VALUES (2, 'Algeria');
INSERT INTO nations (id, name) VALUES (3, 'Andorra');
INSERT INTO nations (id, name) VALUES (4, 'Angola');
INSERT INTO nations (id, name) VALUES (5, 'Antigua and Barbuda');
INSERT INTO nations (id, name) VALUES (6, 'Argentina');
INSERT INTO nations (id, name) VALUES (7, 'Armenia');
INSERT INTO nations (id, name) VALUES (8, 'Australia');
INSERT INTO nations (id, name) VALUES (9, 'Austria');
INSERT INTO nations (id, name) VALUES (10, 'Azerbaijan');
INSERT INTO nations (id, name) VALUES (11, 'Barbados');
INSERT INTO nations (id, name) VALUES (12, 'Belarus');
INSERT INTO nations (id, name) VALUES (13, 'Belgium');
INSERT INTO nations (id, name) VALUES (14, 'Benin');
INSERT INTO nations (id, name) VALUES (15, 'Bermuda');
INSERT INTO nations (id, name) VALUES (16, 'Bolivia');
INSERT INTO nations (id, name) VALUES (17, 'Bosnia and Herzegovina');
INSERT INTO nations (id, name) VALUES (18, 'Brazil');
INSERT INTO nations (id, name) VALUES (19, 'Bulgaria');
INSERT INTO nations (id, name) VALUES (20, 'Burkina Faso');
INSERT INTO nations (id, name) VALUES (21, 'Burundi');
INSERT INTO nations (id, name) VALUES (22, 'Cameroon');
INSERT INTO nations (id, name) VALUES (23, 'Canada');
INSERT INTO nations (id, name) VALUES (24, 'Cape Verde Islands');
INSERT INTO nations (id, name) VALUES (25, 'Central African Republic');
INSERT INTO nations (id, name) VALUES (26, 'Chad');
INSERT INTO nations (id, name) VALUES (27, 'Chile');
INSERT INTO nations (id, name) VALUES (28, 'China PR');
INSERT INTO nations (id, name) VALUES (29, 'Chinese Taipei');
INSERT INTO nations (id, name) VALUES (30, 'Colombia');
INSERT INTO nations (id, name) VALUES (31, 'Congo');
INSERT INTO nations (id, name) VALUES (32, 'Congo DR');
INSERT INTO nations (id, name) VALUES (33, 'Costa Rica');
INSERT INTO nations (id, name) VALUES (34, 'Croatia');
INSERT INTO nations (id, name) VALUES (35, 'Cuba');
INSERT INTO nations (id, name) VALUES (36, 'Cura�ao');
INSERT INTO nations (id, name) VALUES (37, 'Cyprus');
INSERT INTO nations (id, name) VALUES (38, 'Czech Republic');
INSERT INTO nations (id, name) VALUES (39, 'C�te d''Ivoire');
INSERT INTO nations (id, name) VALUES (40, 'Denmark');
INSERT INTO nations (id, name) VALUES (41, 'Dominican Republic');
INSERT INTO nations (id, name) VALUES (42, 'Ecuador');
INSERT INTO nations (id, name) VALUES (43, 'Egypt');
INSERT INTO nations (id, name) VALUES (44, 'El Salvador');
INSERT INTO nations (id, name) VALUES (45, 'England');
INSERT INTO nations (id, name) VALUES (46, 'Equatorial Guinea');
INSERT INTO nations (id, name) VALUES (47, 'Estonia');
INSERT INTO nations (id, name) VALUES (48, 'Faroe Islands');
INSERT INTO nations (id, name) VALUES (49, 'Fiji');
INSERT INTO nations (id, name) VALUES (50, 'Finland');
INSERT INTO nations (id, name) VALUES (51, 'France');
INSERT INTO nations (id, name) VALUES (52, 'Gabon');
INSERT INTO nations (id, name) VALUES (53, 'Gambia');
INSERT INTO nations (id, name) VALUES (54, 'Georgia');
INSERT INTO nations (id, name) VALUES (55, 'Germany');
INSERT INTO nations (id, name) VALUES (56, 'Ghana');
INSERT INTO nations (id, name) VALUES (57, 'Greece');
INSERT INTO nations (id, name) VALUES (58, 'Grenada');
INSERT INTO nations (id, name) VALUES (59, 'Guatemala');
INSERT INTO nations (id, name) VALUES (60, 'Guinea');
INSERT INTO nations (id, name) VALUES (61, 'Guinea-Bissau');
INSERT INTO nations (id, name) VALUES (62, 'Guyana');
INSERT INTO nations (id, name) VALUES (63, 'Haiti');
INSERT INTO nations (id, name) VALUES (64, 'Holland');
INSERT INTO nations (id, name) VALUES (65, 'Honduras');
INSERT INTO nations (id, name) VALUES (66, 'Hong Kong');
INSERT INTO nations (id, name) VALUES (67, 'Hungary');
INSERT INTO nations (id, name) VALUES (68, 'Iceland');
INSERT INTO nations (id, name) VALUES (69, 'India');
INSERT INTO nations (id, name) VALUES (70, 'Indonesia');
INSERT INTO nations (id, name) VALUES (71, 'Iran');
INSERT INTO nations (id, name) VALUES (72, 'Iraq');
INSERT INTO nations (id, name) VALUES (73, 'Israel');
INSERT INTO nations (id, name) VALUES (74, 'Italy');
INSERT INTO nations (id, name) VALUES (75, 'Jamaica');
INSERT INTO nations (id, name) VALUES (76, 'Japan');
INSERT INTO nations (id, name) VALUES (77, 'Jordan');
INSERT INTO nations (id, name) VALUES (78, 'Kazakhstan');
INSERT INTO nations (id, name) VALUES (79, 'Kenya');
INSERT INTO nations (id, name) VALUES (80, 'Korea DPR');
INSERT INTO nations (id, name) VALUES (81, 'Korea Republic');
INSERT INTO nations (id, name) VALUES (82, 'Kosovo');
INSERT INTO nations (id, name) VALUES (83, 'Latvia');
INSERT INTO nations (id, name) VALUES (84, 'Lebanon');
INSERT INTO nations (id, name) VALUES (85, 'Liberia');
INSERT INTO nations (id, name) VALUES (86, 'Libya');
INSERT INTO nations (id, name) VALUES (87, 'Liechtenstein');
INSERT INTO nations (id, name) VALUES (88, 'Lithuania');
INSERT INTO nations (id, name) VALUES (89, 'Luxembourg');
INSERT INTO nations (id, name) VALUES (90, 'Madagascar');
INSERT INTO nations (id, name) VALUES (91, 'Malawi');
INSERT INTO nations (id, name) VALUES (92, 'Mali');
INSERT INTO nations (id, name) VALUES (93, 'Malta');
INSERT INTO nations (id, name) VALUES (94, 'Mauritania');
INSERT INTO nations (id, name) VALUES (95, 'Mexico');
INSERT INTO nations (id, name) VALUES (96, 'Moldova');
INSERT INTO nations (id, name) VALUES (97, 'Montenegro');
INSERT INTO nations (id, name) VALUES (98, 'Montserrat');
INSERT INTO nations (id, name) VALUES (99, 'Morocco');
INSERT INTO nations (id, name) VALUES (100, 'Mozambique');
INSERT INTO nations (id, name) VALUES (101, 'Namibia');
INSERT INTO nations (id, name) VALUES (102, 'Netherlands');
INSERT INTO nations (id, name) VALUES (103, 'New Zealand');
INSERT INTO nations (id, name) VALUES (104, 'Nigeria');
INSERT INTO nations (id, name) VALUES (105, 'North Macedonia');
INSERT INTO nations (id, name) VALUES (106, 'Northern Ireland');
INSERT INTO nations (id, name) VALUES (107, 'Norway');
INSERT INTO nations (id, name) VALUES (108, 'Palestine');
INSERT INTO nations (id, name) VALUES (109, 'Panama');
INSERT INTO nations (id, name) VALUES (110, 'Paraguay');
INSERT INTO nations (id, name) VALUES (111, 'Peru');
INSERT INTO nations (id, name) VALUES (112, 'Philippines');
INSERT INTO nations (id, name) VALUES (113, 'Poland');
INSERT INTO nations (id, name) VALUES (114, 'Portugal');
INSERT INTO nations (id, name) VALUES (115, 'Puerto Rico');
INSERT INTO nations (id, name) VALUES (116, 'Republic of Ireland');
INSERT INTO nations (id, name) VALUES (117, 'Romania');
INSERT INTO nations (id, name) VALUES (118, 'Russia');
INSERT INTO nations (id, name) VALUES (119, 'Rwanda');
INSERT INTO nations (id, name) VALUES (120, 'Saudi Arabia');
INSERT INTO nations (id, name) VALUES (121, 'Scotland');
INSERT INTO nations (id, name) VALUES (122, 'Senegal');
INSERT INTO nations (id, name) VALUES (123, 'Serbia');
INSERT INTO nations (id, name) VALUES (124, 'Sierra Leone');
INSERT INTO nations (id, name) VALUES (125, 'Slovakia');
INSERT INTO nations (id, name) VALUES (126, 'Slovenia');
INSERT INTO nations (id, name) VALUES (127, 'Somalia');
INSERT INTO nations (id, name) VALUES (128, 'South Africa');
INSERT INTO nations (id, name) VALUES (129, 'Spain');
INSERT INTO nations (id, name) VALUES (130, 'Sri Lanka');
INSERT INTO nations (id, name) VALUES (131, 'St. Kitts and Nevis');
INSERT INTO nations (id, name) VALUES (132, 'St. Lucia');
INSERT INTO nations (id, name) VALUES (133, 'Sudan');
INSERT INTO nations (id, name) VALUES (134, 'Suriname');
INSERT INTO nations (id, name) VALUES (135, 'Sweden');
INSERT INTO nations (id, name) VALUES (136, 'Switzerland');
INSERT INTO nations (id, name) VALUES (137, 'Syria');
INSERT INTO nations (id, name) VALUES (138, 'Tanzania');
INSERT INTO nations (id, name) VALUES (139, 'Thailand');
INSERT INTO nations (id, name) VALUES (140, 'Togo');
INSERT INTO nations (id, name) VALUES (141, 'Trinidad and Tobago');
INSERT INTO nations (id, name) VALUES (142, 'Tunisia');
INSERT INTO nations (id, name) VALUES (143, 'Turkey');
INSERT INTO nations (id, name) VALUES (144, 'Uganda');
INSERT INTO nations (id, name) VALUES (145, 'Ukraine');
INSERT INTO nations (id, name) VALUES (146, 'United Arab Emirates');
INSERT INTO nations (id, name) VALUES (147, 'United States');
INSERT INTO nations (id, name) VALUES (148, 'Uruguay');
INSERT INTO nations (id, name) VALUES (149, 'Uzbekistan');
INSERT INTO nations (id, name) VALUES (150, 'Vanuatu');
INSERT INTO nations (id, name) VALUES (151, 'Venezuela');
INSERT INTO nations (id, name) VALUES (152, 'Wales');
INSERT INTO nations (id, name) VALUES (153, 'Zambia');
INSERT INTO nations (id, name) VALUES (154, 'Zimbabwe');

SELECT setval(pg_get_serial_sequence('nations', 'id'), 155, false);

-- migrate:down 

DELETE FROM nations;

SELECT setval(pg_get_serial_sequence('nations', 'id'), 1, false);