-- migrate:up 

INSERT INTO teams (id, name, league_id) VALUES (1, 'Cercle Brugge', 1);
INSERT INTO teams (id, name, league_id) VALUES (2, 'Club Brugge', 1);
INSERT INTO teams (id, name, league_id) VALUES (3, 'FCV Dender EH', 1);
INSERT INTO teams (id, name, league_id) VALUES (4, 'K. Beerschot VA', 1);
INSERT INTO teams (id, name, league_id) VALUES (5, 'KAA Gent', 1);
INSERT INTO teams (id, name, league_id) VALUES (6, 'KRC Genk', 1);
INSERT INTO teams (id, name, league_id) VALUES (7, 'KV Kortrijk', 1);
INSERT INTO teams (id, name, league_id) VALUES (8, 'KV Mechelen', 1);
INSERT INTO teams (id, name, league_id) VALUES (9, 'KVC Westerlo', 1);
INSERT INTO teams (id, name, league_id) VALUES (10, 'OH Leuven', 1);
INSERT INTO teams (id, name, league_id) VALUES (11, 'R. Union St.-G.', 1);
INSERT INTO teams (id, name, league_id) VALUES (12, 'RSC Anderlecht', 1);
INSERT INTO teams (id, name, league_id) VALUES (13, 'Royal Antwerp FC', 1);
INSERT INTO teams (id, name, league_id) VALUES (14, 'STVV', 1);
INSERT INTO teams (id, name, league_id) VALUES (15, 'Sp. Charleroi', 1);
INSERT INTO teams (id, name, league_id) VALUES (16, 'Standard Liège', 1);
INSERT INTO teams (id, name, league_id) VALUES (17, '1860 München', 2);
INSERT INTO teams (id, name, league_id) VALUES (18, 'Aleman. Aachen', 2);
INSERT INTO teams (id, name, league_id) VALUES (19, 'Arminia Bielefeld', 2);
INSERT INTO teams (id, name, league_id) VALUES (20, 'B. Dortmund II', 2);
INSERT INTO teams (id, name, league_id) VALUES (21, 'Dynamo Dresden', 2);
INSERT INTO teams (id, name, league_id) VALUES (22, 'Energie Cottbus', 2);
INSERT INTO teams (id, name, league_id) VALUES (23, 'FC Erzgebirge Aue', 2);
INSERT INTO teams (id, name, league_id) VALUES (24, 'FC Hansa Rostock', 2);
INSERT INTO teams (id, name, league_id) VALUES (25, 'FC Ingolstadt 04', 2);
INSERT INTO teams (id, name, league_id) VALUES (26, 'Hannover 96 II', 2);
INSERT INTO teams (id, name, league_id) VALUES (27, 'Rot-Weiss Essen', 2);
INSERT INTO teams (id, name, league_id) VALUES (28, 'SC Verl', 2);
INSERT INTO teams (id, name, league_id) VALUES (29, 'SV Sandhausen', 2);
INSERT INTO teams (id, name, league_id) VALUES (30, 'SV Waldhof', 2);
INSERT INTO teams (id, name, league_id) VALUES (31, 'Saarbrücken', 2);
INSERT INTO teams (id, name, league_id) VALUES (32, 'Unterhaching', 2);
INSERT INTO teams (id, name, league_id) VALUES (33, 'VfB Stuttgart II', 2);
INSERT INTO teams (id, name, league_id) VALUES (34, 'VfL Osnabrück', 2);
INSERT INTO teams (id, name, league_id) VALUES (35, 'Viktoria Köln', 2);
INSERT INTO teams (id, name, league_id) VALUES (36, 'Wehen Wiesbaden', 2);
INSERT INTO teams (id, name, league_id) VALUES (37, 'AGF', 3);
INSERT INTO teams (id, name, league_id) VALUES (38, 'AaB', 3);
INSERT INTO teams (id, name, league_id) VALUES (39, 'Brøndby IF', 3);
INSERT INTO teams (id, name, league_id) VALUES (40, 'F.C. København', 3);
INSERT INTO teams (id, name, league_id) VALUES (41, 'FC Midtjylland', 3);
INSERT INTO teams (id, name, league_id) VALUES (42, 'FC Nordsjælland', 3);
INSERT INTO teams (id, name, league_id) VALUES (43, 'Lyngby BK', 3);
INSERT INTO teams (id, name, league_id) VALUES (44, 'Randers FC', 3);
INSERT INTO teams (id, name, league_id) VALUES (45, 'Silkeborg IF', 3);
INSERT INTO teams (id, name, league_id) VALUES (46, 'Sønderjyske', 3);
INSERT INTO teams (id, name, league_id) VALUES (47, 'Vejle Boldklub', 3);
INSERT INTO teams (id, name, league_id) VALUES (48, 'Viborg FF', 3);
INSERT INTO teams (id, name, league_id) VALUES (49, 'Adelaide United', 4);
INSERT INTO teams (id, name, league_id) VALUES (50, 'Auckland FC', 4);
INSERT INTO teams (id, name, league_id) VALUES (51, 'Brisbane Roar', 4);
INSERT INTO teams (id, name, league_id) VALUES (52, 'Central Coast', 4);
INSERT INTO teams (id, name, league_id) VALUES (53, 'Macarthur FC', 4);
INSERT INTO teams (id, name, league_id) VALUES (54, 'Melb. Victory', 4);
INSERT INTO teams (id, name, league_id) VALUES (55, 'Melbourne City', 4);
INSERT INTO teams (id, name, league_id) VALUES (56, 'Newcastle Jets', 4);
INSERT INTO teams (id, name, league_id) VALUES (57, 'Perth Glory', 4);
INSERT INTO teams (id, name, league_id) VALUES (58, 'Sydney FC', 4);
INSERT INTO teams (id, name, league_id) VALUES (59, 'WS Wanderers', 4);
INSERT INTO teams (id, name, league_id) VALUES (60, 'Well. Phoenix', 4);
INSERT INTO teams (id, name, league_id) VALUES (61, 'Western United', 4);
INSERT INTO teams (id, name, league_id) VALUES (62, 'AIK', 5);
INSERT INTO teams (id, name, league_id) VALUES (63, 'BK Häcken', 5);
INSERT INTO teams (id, name, league_id) VALUES (64, 'Brommapojkarna', 5);
INSERT INTO teams (id, name, league_id) VALUES (65, 'Djurgårdens IF', 5);
INSERT INTO teams (id, name, league_id) VALUES (66, 'GAIS', 5);
INSERT INTO teams (id, name, league_id) VALUES (67, 'Halmstads BK', 5);
INSERT INTO teams (id, name, league_id) VALUES (68, 'Hammarby IF', 5);
INSERT INTO teams (id, name, league_id) VALUES (69, 'IF Elfsborg', 5);
INSERT INTO teams (id, name, league_id) VALUES (70, 'IFK Göteborg', 5);
INSERT INTO teams (id, name, league_id) VALUES (71, 'IFK Norrköping', 5);
INSERT INTO teams (id, name, league_id) VALUES (72, 'IFK Värnamo', 5);
INSERT INTO teams (id, name, league_id) VALUES (73, 'IK Sirius', 5);
INSERT INTO teams (id, name, league_id) VALUES (74, 'Kalmar FF', 5);
INSERT INTO teams (id, name, league_id) VALUES (75, 'Malmö FF', 5);
INSERT INTO teams (id, name, league_id) VALUES (76, 'Mjällby AIF', 5);
INSERT INTO teams (id, name, league_id) VALUES (77, 'Västerås SK', 5);
INSERT INTO teams (id, name, league_id) VALUES (78, 'AS Saint Étienne', 6);
INSERT INTO teams (id, name, league_id) VALUES (79, 'Dijon FCO', 6);
INSERT INTO teams (id, name, league_id) VALUES (80, 'En Avant Guingamp', 6);
INSERT INTO teams (id, name, league_id) VALUES (81, 'FC Fleury 91', 6);
INSERT INTO teams (id, name, league_id) VALUES (82, 'FC Nantes', 6);
INSERT INTO teams (id, name, league_id) VALUES (83, 'Havre AC', 6);
INSERT INTO teams (id, name, league_id) VALUES (84, 'Montpellier', 6);
INSERT INTO teams (id, name, league_id) VALUES (85, 'OL', 6);
INSERT INTO teams (id, name, league_id) VALUES (86, 'Paris FC', 6);
INSERT INTO teams (id, name, league_id) VALUES (87, 'Paris SG', 6);
INSERT INTO teams (id, name, league_id) VALUES (88, 'Stade de Reims', 6);
INSERT INTO teams (id, name, league_id) VALUES (89, 'Strasbourg', 6);
INSERT INTO teams (id, name, league_id) VALUES (90, 'Arsenal', 7);
INSERT INTO teams (id, name, league_id) VALUES (91, 'Aston Villa', 7);
INSERT INTO teams (id, name, league_id) VALUES (92, 'Brighton', 7);
INSERT INTO teams (id, name, league_id) VALUES (93, 'Chelsea', 7);
INSERT INTO teams (id, name, league_id) VALUES (94, 'Crystal Palace', 7);
INSERT INTO teams (id, name, league_id) VALUES (95, 'Everton', 7);
INSERT INTO teams (id, name, league_id) VALUES (96, 'Leicester City', 7);
INSERT INTO teams (id, name, league_id) VALUES (97, 'Liverpool', 7);
INSERT INTO teams (id, name, league_id) VALUES (98, 'Manchester City', 7);
INSERT INTO teams (id, name, league_id) VALUES (99, 'Manchester Utd', 7);
INSERT INTO teams (id, name, league_id) VALUES (100, 'Spurs', 7);
INSERT INTO teams (id, name, league_id) VALUES (101, 'West Ham', 7);
INSERT INTO teams (id, name, league_id) VALUES (102, '1. FSV Mainz 05', 8);
INSERT INTO teams (id, name, league_id) VALUES (103, 'Borussia Dortmund', 8);
INSERT INTO teams (id, name, league_id) VALUES (104, 'FC Augsburg', 8);
INSERT INTO teams (id, name, league_id) VALUES (105, 'FC Bayern München', 8);
INSERT INTO teams (id, name, league_id) VALUES (106, 'FC St. Pauli', 8);
INSERT INTO teams (id, name, league_id) VALUES (107, 'Frankfurt', 8);
INSERT INTO teams (id, name, league_id) VALUES (108, 'Heidenheim', 8);
INSERT INTO teams (id, name, league_id) VALUES (109, 'Holstein Kiel', 8);
INSERT INTO teams (id, name, league_id) VALUES (110, 'Leverkusen', 8);
INSERT INTO teams (id, name, league_id) VALUES (111, 'M''gladbach', 8);
INSERT INTO teams (id, name, league_id) VALUES (112, 'RB Leipzig', 8);
INSERT INTO teams (id, name, league_id) VALUES (113, 'SC Freiburg', 8);
INSERT INTO teams (id, name, league_id) VALUES (114, 'SV Werder Bremen', 8);
INSERT INTO teams (id, name, league_id) VALUES (115, 'TSG Hoffenheim', 8);
INSERT INTO teams (id, name, league_id) VALUES (116, 'Union Berlin', 8);
INSERT INTO teams (id, name, league_id) VALUES (117, 'VfB Stuttgart', 8);
INSERT INTO teams (id, name, league_id) VALUES (118, 'VfL Bochum 1848', 8);
INSERT INTO teams (id, name, league_id) VALUES (119, 'VfL Wolfsburg', 8);
INSERT INTO teams (id, name, league_id) VALUES (120, '1. FC Köln', 9);
INSERT INTO teams (id, name, league_id) VALUES (121, '1. FC Magdeburg', 9);
INSERT INTO teams (id, name, league_id) VALUES (122, '1. FC Nürnberg', 9);
INSERT INTO teams (id, name, league_id) VALUES (123, 'Braunschweig', 9);
INSERT INTO teams (id, name, league_id) VALUES (124, 'Düsseldorf', 9);
INSERT INTO teams (id, name, league_id) VALUES (125, 'FC Schalke 04', 9);
INSERT INTO teams (id, name, league_id) VALUES (126, 'Fürth', 9);
INSERT INTO teams (id, name, league_id) VALUES (127, 'Hamburger SV', 9);
INSERT INTO teams (id, name, league_id) VALUES (128, 'Hannover 96', 9);
INSERT INTO teams (id, name, league_id) VALUES (129, 'Hertha BSC', 9);
INSERT INTO teams (id, name, league_id) VALUES (130, 'Jahn Regensburg', 9);
INSERT INTO teams (id, name, league_id) VALUES (131, 'Kaiserslautern', 9);
INSERT INTO teams (id, name, league_id) VALUES (132, 'Karlsruher SC', 9);
INSERT INTO teams (id, name, league_id) VALUES (133, 'Preußen Münster', 9);
INSERT INTO teams (id, name, league_id) VALUES (134, 'SC Paderborn 07', 9);
INSERT INTO teams (id, name, league_id) VALUES (135, 'SSV Ulm 1846', 9);
INSERT INTO teams (id, name, league_id) VALUES (136, 'SV Darmstadt 98', 9);
INSERT INTO teams (id, name, league_id) VALUES (137, 'SV Elversberg', 9);
INSERT INTO teams (id, name, league_id) VALUES (138, 'Beijing FC', 10);
INSERT INTO teams (id, name, league_id) VALUES (139, 'Cangzhou FC', 10);
INSERT INTO teams (id, name, league_id) VALUES (140, 'Changchun Yatai', 10);
INSERT INTO teams (id, name, league_id) VALUES (141, 'Henan FC', 10);
INSERT INTO teams (id, name, league_id) VALUES (142, 'Meizhou Hakka FC', 10);
INSERT INTO teams (id, name, league_id) VALUES (143, 'Nantong Zhiyun FC', 10);
INSERT INTO teams (id, name, league_id) VALUES (144, 'Qingdao Hainiu', 10);
INSERT INTO teams (id, name, league_id) VALUES (145, 'Qingdao W. Coast', 10);
INSERT INTO teams (id, name, league_id) VALUES (146, 'Rongcheng FC', 10);
INSERT INTO teams (id, name, league_id) VALUES (147, 'SZ Peng City', 10);
INSERT INTO teams (id, name, league_id) VALUES (148, 'Shandong Taishan', 10);
INSERT INTO teams (id, name, league_id) VALUES (149, 'Shanghai Port FC', 10);
INSERT INTO teams (id, name, league_id) VALUES (150, 'Shanghai Shenhua', 10);
INSERT INTO teams (id, name, league_id) VALUES (151, 'Tianjin JMT FC', 10);
INSERT INTO teams (id, name, league_id) VALUES (152, 'Wuhan Three Towns', 10);
INSERT INTO teams (id, name, league_id) VALUES (153, 'Zhejiang Pro', 10);
INSERT INTO teams (id, name, league_id) VALUES (154, 'BSC Young Boys', 11);
INSERT INTO teams (id, name, league_id) VALUES (155, 'FC Basel 1893', 11);
INSERT INTO teams (id, name, league_id) VALUES (156, 'FC Lugano', 11);
INSERT INTO teams (id, name, league_id) VALUES (157, 'FC Luzern', 11);
INSERT INTO teams (id, name, league_id) VALUES (158, 'FC Sion', 11);
INSERT INTO teams (id, name, league_id) VALUES (159, 'FC St. Gallen', 11);
INSERT INTO teams (id, name, league_id) VALUES (160, 'FC Winterthur', 11);
INSERT INTO teams (id, name, league_id) VALUES (161, 'FC Zürich', 11);
INSERT INTO teams (id, name, league_id) VALUES (162, 'GC Zürich', 11);
INSERT INTO teams (id, name, league_id) VALUES (163, 'Lausanne-Sport', 11);
INSERT INTO teams (id, name, league_id) VALUES (164, 'Servette FC', 11);
INSERT INTO teams (id, name, league_id) VALUES (165, 'Yverdon Sport FC', 11);
INSERT INTO teams (id, name, league_id) VALUES (166, 'Juventus', 12);
INSERT INTO teams (id, name, league_id) VALUES (167, 'Roma', 12);
INSERT INTO teams (id, name, league_id) VALUES (168, 'Slavia Praha', 13);
INSERT INTO teams (id, name, league_id) VALUES (169, 'Blackburn Rovers', 14);
INSERT INTO teams (id, name, league_id) VALUES (170, 'Bristol City', 14);
INSERT INTO teams (id, name, league_id) VALUES (171, 'Burnley', 14);
INSERT INTO teams (id, name, league_id) VALUES (172, 'Cardiff City', 14);
INSERT INTO teams (id, name, league_id) VALUES (173, 'Coventry City', 14);
INSERT INTO teams (id, name, league_id) VALUES (174, 'Derby County', 14);
INSERT INTO teams (id, name, league_id) VALUES (175, 'Hull City', 14);
INSERT INTO teams (id, name, league_id) VALUES (176, 'Leeds United', 14);
INSERT INTO teams (id, name, league_id) VALUES (177, 'Luton Town', 14);
INSERT INTO teams (id, name, league_id) VALUES (178, 'Middlesbrough', 14);
INSERT INTO teams (id, name, league_id) VALUES (179, 'Millwall', 14);
INSERT INTO teams (id, name, league_id) VALUES (180, 'Norwich', 14);
INSERT INTO teams (id, name, league_id) VALUES (181, 'Oxford United', 14);
INSERT INTO teams (id, name, league_id) VALUES (182, 'Plymouth Argyle', 14);
INSERT INTO teams (id, name, league_id) VALUES (183, 'Portsmouth', 14);
INSERT INTO teams (id, name, league_id) VALUES (184, 'Preston', 14);
INSERT INTO teams (id, name, league_id) VALUES (185, 'QPR', 14);
INSERT INTO teams (id, name, league_id) VALUES (186, 'Sheffield Utd', 14);
INSERT INTO teams (id, name, league_id) VALUES (187, 'Sheffield Wed', 14);
INSERT INTO teams (id, name, league_id) VALUES (188, 'Stoke City', 14);
INSERT INTO teams (id, name, league_id) VALUES (189, 'Sunderland', 14);
INSERT INTO teams (id, name, league_id) VALUES (190, 'Swansea City', 14);
INSERT INTO teams (id, name, league_id) VALUES (191, 'Watford', 14);
INSERT INTO teams (id, name, league_id) VALUES (192, 'West Brom', 14);
INSERT INTO teams (id, name, league_id) VALUES (193, 'Barnsley', 15);
INSERT INTO teams (id, name, league_id) VALUES (194, 'Birmingham City', 15);
INSERT INTO teams (id, name, league_id) VALUES (195, 'Blackpool', 15);
INSERT INTO teams (id, name, league_id) VALUES (196, 'Bolton', 15);
INSERT INTO teams (id, name, league_id) VALUES (197, 'Bristol Rovers', 15);
INSERT INTO teams (id, name, league_id) VALUES (198, 'Burton Albion', 15);
INSERT INTO teams (id, name, league_id) VALUES (199, 'Cambridge Utd', 15);
INSERT INTO teams (id, name, league_id) VALUES (200, 'Charlton Ath', 15);
INSERT INTO teams (id, name, league_id) VALUES (201, 'Crawley Town', 15);
INSERT INTO teams (id, name, league_id) VALUES (202, 'Exeter City', 15);
INSERT INTO teams (id, name, league_id) VALUES (203, 'Huddersfield', 15);
INSERT INTO teams (id, name, league_id) VALUES (204, 'Leyton Orient', 15);
INSERT INTO teams (id, name, league_id) VALUES (205, 'Lincoln City', 15);
INSERT INTO teams (id, name, league_id) VALUES (206, 'Mansfield Town', 15);
INSERT INTO teams (id, name, league_id) VALUES (207, 'Northampton', 15);
INSERT INTO teams (id, name, league_id) VALUES (208, 'Peterborough', 15);
INSERT INTO teams (id, name, league_id) VALUES (209, 'Reading', 15);
INSERT INTO teams (id, name, league_id) VALUES (210, 'Rotherham Utd', 15);
INSERT INTO teams (id, name, league_id) VALUES (211, 'Shrewsbury', 15);
INSERT INTO teams (id, name, league_id) VALUES (212, 'Stevenage', 15);
INSERT INTO teams (id, name, league_id) VALUES (213, 'Stockport', 15);
INSERT INTO teams (id, name, league_id) VALUES (214, 'Wigan Athletic', 15);
INSERT INTO teams (id, name, league_id) VALUES (215, 'Wrexham', 15);
INSERT INTO teams (id, name, league_id) VALUES (216, 'Wycombe', 15);
INSERT INTO teams (id, name, league_id) VALUES (217, 'AFC Wimbledon', 16);
INSERT INTO teams (id, name, league_id) VALUES (218, 'Accrington', 16);
INSERT INTO teams (id, name, league_id) VALUES (219, 'Barrow', 16);
INSERT INTO teams (id, name, league_id) VALUES (220, 'Bradford City', 16);
INSERT INTO teams (id, name, league_id) VALUES (221, 'Bromley FC', 16);
INSERT INTO teams (id, name, league_id) VALUES (222, 'Carlisle United', 16);
INSERT INTO teams (id, name, league_id) VALUES (223, 'Cheltenham Town', 16);
INSERT INTO teams (id, name, league_id) VALUES (224, 'Chesterfield', 16);
INSERT INTO teams (id, name, league_id) VALUES (225, 'Colchester', 16);
INSERT INTO teams (id, name, league_id) VALUES (226, 'Crewe Alexandra', 16);
INSERT INTO teams (id, name, league_id) VALUES (227, 'Doncaster', 16);
INSERT INTO teams (id, name, league_id) VALUES (228, 'Fleetwood Town', 16);
INSERT INTO teams (id, name, league_id) VALUES (229, 'Gillingham', 16);
INSERT INTO teams (id, name, league_id) VALUES (230, 'Grimsby Town', 16);
INSERT INTO teams (id, name, league_id) VALUES (231, 'Harrogate Town', 16);
INSERT INTO teams (id, name, league_id) VALUES (232, 'MK Dons', 16);
INSERT INTO teams (id, name, league_id) VALUES (233, 'Morecambe', 16);
INSERT INTO teams (id, name, league_id) VALUES (234, 'Newport County', 16);
INSERT INTO teams (id, name, league_id) VALUES (235, 'Notts County', 16);
INSERT INTO teams (id, name, league_id) VALUES (236, 'Port Vale', 16);
INSERT INTO teams (id, name, league_id) VALUES (237, 'Salford City', 16);
INSERT INTO teams (id, name, league_id) VALUES (238, 'Swindon Town', 16);
INSERT INTO teams (id, name, league_id) VALUES (239, 'Tranmere Rovers', 16);
INSERT INTO teams (id, name, league_id) VALUES (240, 'Walsall', 16);
INSERT INTO teams (id, name, league_id) VALUES (241, 'FK Bodø/Glimt', 17);
INSERT INTO teams (id, name, league_id) VALUES (242, 'FK Haugesund', 17);
INSERT INTO teams (id, name, league_id) VALUES (243, 'Fredrikstad FK', 17);
INSERT INTO teams (id, name, league_id) VALUES (244, 'HamKam Fotball', 17);
INSERT INTO teams (id, name, league_id) VALUES (245, 'KFUM-Kameratene', 17);
INSERT INTO teams (id, name, league_id) VALUES (246, 'Kristiansund BK', 17);
INSERT INTO teams (id, name, league_id) VALUES (247, 'Lillestrøm SK', 17);
INSERT INTO teams (id, name, league_id) VALUES (248, 'Molde FK', 17);
INSERT INTO teams (id, name, league_id) VALUES (249, 'Odds BK', 17);
INSERT INTO teams (id, name, league_id) VALUES (250, 'Rosenborg BK', 17);
INSERT INTO teams (id, name, league_id) VALUES (251, 'SK Brann', 17);
INSERT INTO teams (id, name, league_id) VALUES (252, 'Sandefjord', 17);
INSERT INTO teams (id, name, league_id) VALUES (253, 'Sarpsborg 08', 17);
INSERT INTO teams (id, name, league_id) VALUES (254, 'Strømsgodset IF', 17);
INSERT INTO teams (id, name, league_id) VALUES (255, 'Tromsø IL', 17);
INSERT INTO teams (id, name, league_id) VALUES (256, 'Viking FK', 17);
INSERT INTO teams (id, name, league_id) VALUES (257, 'AZ', 18);
INSERT INTO teams (id, name, league_id) VALUES (258, 'Ajax', 18);
INSERT INTO teams (id, name, league_id) VALUES (259, 'Almere City FC', 18);
INSERT INTO teams (id, name, league_id) VALUES (260, 'FC Groningen', 18);
INSERT INTO teams (id, name, league_id) VALUES (261, 'FC Twente', 18);
INSERT INTO teams (id, name, league_id) VALUES (262, 'FC Utrecht', 18);
INSERT INTO teams (id, name, league_id) VALUES (263, 'Feyenoord', 18);
INSERT INTO teams (id, name, league_id) VALUES (264, 'Fortuna Sittard', 18);
INSERT INTO teams (id, name, league_id) VALUES (265, 'Go Ahead Eagles', 18);
INSERT INTO teams (id, name, league_id) VALUES (266, 'Heracles Almelo', 18);
INSERT INTO teams (id, name, league_id) VALUES (267, 'N.E.C. Nijmegen', 18);
INSERT INTO teams (id, name, league_id) VALUES (268, 'NAC Breda', 18);
INSERT INTO teams (id, name, league_id) VALUES (269, 'PEC Zwolle', 18);
INSERT INTO teams (id, name, league_id) VALUES (270, 'PSV', 18);
INSERT INTO teams (id, name, league_id) VALUES (271, 'RKC Waalwijk', 18);
INSERT INTO teams (id, name, league_id) VALUES (272, 'Sparta Rotterdam', 18);
INSERT INTO teams (id, name, league_id) VALUES (273, 'Willem II', 18);
INSERT INTO teams (id, name, league_id) VALUES (274, 'sc Heerenveen', 18);
INSERT INTO teams (id, name, league_id) VALUES (275, 'HJK Helsinki', 19);
INSERT INTO teams (id, name, league_id) VALUES (276, '1. FC Köln', 20);
INSERT INTO teams (id, name, league_id) VALUES (277, 'Carl Zeiss Jena', 20);
INSERT INTO teams (id, name, league_id) VALUES (278, 'FC Bayern München', 20);
INSERT INTO teams (id, name, league_id) VALUES (279, 'Frankfurt', 20);
INSERT INTO teams (id, name, league_id) VALUES (280, 'Leverkusen', 20);
INSERT INTO teams (id, name, league_id) VALUES (281, 'RB Leipzig', 20);
INSERT INTO teams (id, name, league_id) VALUES (282, 'SC Freiburg', 20);
INSERT INTO teams (id, name, league_id) VALUES (283, 'SGS Essen', 20);
INSERT INTO teams (id, name, league_id) VALUES (284, 'SV Werder Bremen', 20);
INSERT INTO teams (id, name, league_id) VALUES (285, 'TSG Hoffenheim', 20);
INSERT INTO teams (id, name, league_id) VALUES (286, 'Turbine Potsdam', 20);
INSERT INTO teams (id, name, league_id) VALUES (287, 'VfL Wolfsburg', 20);
INSERT INTO teams (id, name, league_id) VALUES (288, 'AEK Athens', 21);
INSERT INTO teams (id, name, league_id) VALUES (289, 'Olympiacos FC', 21);
INSERT INTO teams (id, name, league_id) VALUES (290, 'PAOK FC', 21);
INSERT INTO teams (id, name, league_id) VALUES (291, 'Panathinaikos', 21);
INSERT INTO teams (id, name, league_id) VALUES (292, 'Bengaluru FC', 22);
INSERT INTO teams (id, name, league_id) VALUES (293, 'Chennaiyin FC', 22);
INSERT INTO teams (id, name, league_id) VALUES (294, 'East Bengal', 22);
INSERT INTO teams (id, name, league_id) VALUES (295, 'FC Goa', 22);
INSERT INTO teams (id, name, league_id) VALUES (296, 'Hyderabad FC', 22);
INSERT INTO teams (id, name, league_id) VALUES (297, 'Jamshedpur FC', 22);
INSERT INTO teams (id, name, league_id) VALUES (298, 'Kerala Blasters', 22);
INSERT INTO teams (id, name, league_id) VALUES (299, 'Mohammedan SC', 22);
INSERT INTO teams (id, name, league_id) VALUES (300, 'Mohun Bagan SG', 22);
INSERT INTO teams (id, name, league_id) VALUES (301, 'Mumbai City FC', 22);
INSERT INTO teams (id, name, league_id) VALUES (302, 'NorthEast United', 22);
INSERT INTO teams (id, name, league_id) VALUES (303, 'Odisha FC', 22);
INSERT INTO teams (id, name, league_id) VALUES (304, 'Punjab FC', 22);
INSERT INTO teams (id, name, league_id) VALUES (305, 'Daegu FC', 23);
INSERT INTO teams (id, name, league_id) VALUES (306, 'Daejeon', 23);
INSERT INTO teams (id, name, league_id) VALUES (307, 'FC Seoul', 23);
INSERT INTO teams (id, name, league_id) VALUES (308, 'Gangwon FC', 23);
INSERT INTO teams (id, name, league_id) VALUES (309, 'Gimcheon Sangmu', 23);
INSERT INTO teams (id, name, league_id) VALUES (310, 'GwangJu FC', 23);
INSERT INTO teams (id, name, league_id) VALUES (311, 'Incheon United', 23);
INSERT INTO teams (id, name, league_id) VALUES (312, 'Jeju United', 23);
INSERT INTO teams (id, name, league_id) VALUES (313, 'Jeonbuk Hyundai', 23);
INSERT INTO teams (id, name, league_id) VALUES (314, 'Pohang Steelers', 23);
INSERT INTO teams (id, name, league_id) VALUES (315, 'Suwon FC', 23);
INSERT INTO teams (id, name, league_id) VALUES (316, 'Ulsan Hyundai', 23);
INSERT INTO teams (id, name, league_id) VALUES (317, 'Athletic Club', 24);
INSERT INTO teams (id, name, league_id) VALUES (318, 'Atlético de Madrid', 24);
INSERT INTO teams (id, name, league_id) VALUES (319, 'CA Osasuna', 24);
INSERT INTO teams (id, name, league_id) VALUES (320, 'CD Leganés', 24);
INSERT INTO teams (id, name, league_id) VALUES (321, 'D. Alavés', 24);
INSERT INTO teams (id, name, league_id) VALUES (322, 'FC Barcelona', 24);
INSERT INTO teams (id, name, league_id) VALUES (323, 'Getafe CF', 24);
INSERT INTO teams (id, name, league_id) VALUES (324, 'Girona FC', 24);
INSERT INTO teams (id, name, league_id) VALUES (325, 'R. Valladolid CF', 24);
INSERT INTO teams (id, name, league_id) VALUES (326, 'RC Celta', 24);
INSERT INTO teams (id, name, league_id) VALUES (327, 'RCD Espanyol', 24);
INSERT INTO teams (id, name, league_id) VALUES (328, 'RCD Mallorca', 24);
INSERT INTO teams (id, name, league_id) VALUES (329, 'Rayo Vallecano', 24);
INSERT INTO teams (id, name, league_id) VALUES (330, 'Real Betis', 24);
INSERT INTO teams (id, name, league_id) VALUES (331, 'Real Madrid', 24);
INSERT INTO teams (id, name, league_id) VALUES (332, 'Real Sociedad', 24);
INSERT INTO teams (id, name, league_id) VALUES (333, 'Sevilla FC', 24);
INSERT INTO teams (id, name, league_id) VALUES (334, 'UD Las Palmas', 24);
INSERT INTO teams (id, name, league_id) VALUES (335, 'Valencia CF', 24);
INSERT INTO teams (id, name, league_id) VALUES (336, 'Villarreal CF', 24);
INSERT INTO teams (id, name, league_id) VALUES (337, 'Albacete BP', 25);
INSERT INTO teams (id, name, league_id) VALUES (338, 'Burgos CF', 25);
INSERT INTO teams (id, name, league_id) VALUES (339, 'CD Castellón', 25);
INSERT INTO teams (id, name, league_id) VALUES (340, 'CD Eldense', 25);
INSERT INTO teams (id, name, league_id) VALUES (341, 'CD Mirandés', 25);
INSERT INTO teams (id, name, league_id) VALUES (342, 'CD Tenerife', 25);
INSERT INTO teams (id, name, league_id) VALUES (343, 'Cádiz CF', 25);
INSERT INTO teams (id, name, league_id) VALUES (344, 'Córdoba CF', 25);
INSERT INTO teams (id, name, league_id) VALUES (345, 'Elche CF', 25);
INSERT INTO teams (id, name, league_id) VALUES (346, 'FC Cartagena', 25);
INSERT INTO teams (id, name, league_id) VALUES (347, 'Granada CF', 25);
INSERT INTO teams (id, name, league_id) VALUES (348, 'Levante UD', 25);
INSERT INTO teams (id, name, league_id) VALUES (349, 'Málaga CF', 25);
INSERT INTO teams (id, name, league_id) VALUES (350, 'R. Oviedo', 25);
INSERT INTO teams (id, name, league_id) VALUES (351, 'R. Racing Club', 25);
INSERT INTO teams (id, name, league_id) VALUES (352, 'R. Sporting', 25);
INSERT INTO teams (id, name, league_id) VALUES (353, 'RC Deportivo', 25);
INSERT INTO teams (id, name, league_id) VALUES (354, 'Racing de Ferrol', 25);
INSERT INTO teams (id, name, league_id) VALUES (355, 'Real Zaragoza', 25);
INSERT INTO teams (id, name, league_id) VALUES (356, 'SD Eibar', 25);
INSERT INTO teams (id, name, league_id) VALUES (357, 'SD Huesca', 25);
INSERT INTO teams (id, name, league_id) VALUES (358, 'UD Almería', 25);
INSERT INTO teams (id, name, league_id) VALUES (359, 'Alianza Lima', 26);
INSERT INTO teams (id, name, league_id) VALUES (360, 'Barcelona SC', 26);
INSERT INTO teams (id, name, league_id) VALUES (361, 'Bolívar', 26);
INSERT INTO teams (id, name, league_id) VALUES (362, 'Caracas FC', 26);
INSERT INTO teams (id, name, league_id) VALUES (363, 'Cerro Porteño', 26);
INSERT INTO teams (id, name, league_id) VALUES (364, 'Cobresal', 26);
INSERT INTO teams (id, name, league_id) VALUES (365, 'Colo-Colo', 26);
INSERT INTO teams (id, name, league_id) VALUES (366, 'Dep. Táchira', 26);
INSERT INTO teams (id, name, league_id) VALUES (367, 'Estudiantes', 26);
INSERT INTO teams (id, name, league_id) VALUES (368, 'Huachipato', 26);
INSERT INTO teams (id, name, league_id) VALUES (369, 'IDV', 26);
INSERT INTO teams (id, name, league_id) VALUES (370, 'Junior', 26);
INSERT INTO teams (id, name, league_id) VALUES (371, 'LDU Quito', 26);
INSERT INTO teams (id, name, league_id) VALUES (372, 'Libertad', 26);
INSERT INTO teams (id, name, league_id) VALUES (373, 'Liverpool', 26);
INSERT INTO teams (id, name, league_id) VALUES (374, 'Millonarios', 26);
INSERT INTO teams (id, name, league_id) VALUES (375, 'Nacional', 26);
INSERT INTO teams (id, name, league_id) VALUES (376, 'Palestino', 26);
INSERT INTO teams (id, name, league_id) VALUES (377, 'Peñarol', 26);
INSERT INTO teams (id, name, league_id) VALUES (378, 'River Plate', 26);
INSERT INTO teams (id, name, league_id) VALUES (379, 'Rosario Central', 26);
INSERT INTO teams (id, name, league_id) VALUES (380, 'San Lorenzo', 26);
INSERT INTO teams (id, name, league_id) VALUES (381, 'Talleres', 26);
INSERT INTO teams (id, name, league_id) VALUES (382, 'The Strongest', 26);
INSERT INTO teams (id, name, league_id) VALUES (383, 'Universitario', 26);
INSERT INTO teams (id, name, league_id) VALUES (384, 'Qarabağ FK', 27);
INSERT INTO teams (id, name, league_id) VALUES (385, 'Atl. Nacional', 28);
INSERT INTO teams (id, name, league_id) VALUES (386, 'APOEL FC', 29);
INSERT INTO teams (id, name, league_id) VALUES (387, 'Athletic Club', 30);
INSERT INTO teams (id, name, league_id) VALUES (388, 'Atlético de Madrid', 30);
INSERT INTO teams (id, name, league_id) VALUES (389, 'FC Barcelona', 30);
INSERT INTO teams (id, name, league_id) VALUES (390, 'Granada CF', 30);
INSERT INTO teams (id, name, league_id) VALUES (391, 'Levante Badalona', 30);
INSERT INTO teams (id, name, league_id) VALUES (392, 'Levante UD', 30);
INSERT INTO teams (id, name, league_id) VALUES (393, 'Madrid CFF', 30);
INSERT INTO teams (id, name, league_id) VALUES (394, 'RC Deportivo', 30);
INSERT INTO teams (id, name, league_id) VALUES (395, 'RCD Espanyol', 30);
INSERT INTO teams (id, name, league_id) VALUES (396, 'Real Betis', 30);
INSERT INTO teams (id, name, league_id) VALUES (397, 'Real Madrid CF', 30);
INSERT INTO teams (id, name, league_id) VALUES (398, 'Real Sociedad', 30);
INSERT INTO teams (id, name, league_id) VALUES (399, 'SD Eibar', 30);
INSERT INTO teams (id, name, league_id) VALUES (400, 'Sevilla FC', 30);
INSERT INTO teams (id, name, league_id) VALUES (401, 'UD Tenerife', 30);
INSERT INTO teams (id, name, league_id) VALUES (402, 'Valencia CF', 30);
INSERT INTO teams (id, name, league_id) VALUES (403, 'Dinamo Zagreb', 31);
INSERT INTO teams (id, name, league_id) VALUES (404, 'Hajduk Split', 31);
INSERT INTO teams (id, name, league_id) VALUES (405, 'AVS Futebol SAD', 32);
INSERT INTO teams (id, name, league_id) VALUES (406, 'Arouca', 32);
INSERT INTO teams (id, name, league_id) VALUES (407, 'Boavista FC', 32);
INSERT INTO teams (id, name, league_id) VALUES (408, 'Casa Pia AC', 32);
INSERT INTO teams (id, name, league_id) VALUES (409, 'Estoril Praia', 32);
INSERT INTO teams (id, name, league_id) VALUES (410, 'Estrela Amadora', 32);
INSERT INTO teams (id, name, league_id) VALUES (411, 'FC Famalicão', 32);
INSERT INTO teams (id, name, league_id) VALUES (412, 'FC Porto', 32);
INSERT INTO teams (id, name, league_id) VALUES (413, 'Farense', 32);
INSERT INTO teams (id, name, league_id) VALUES (414, 'Gil Vicente', 32);
INSERT INTO teams (id, name, league_id) VALUES (415, 'Moreirense FC', 32);
INSERT INTO teams (id, name, league_id) VALUES (416, 'Nacional', 32);
INSERT INTO teams (id, name, league_id) VALUES (417, 'Rio Ave FC', 32);
INSERT INTO teams (id, name, league_id) VALUES (418, 'SC Braga', 32);
INSERT INTO teams (id, name, league_id) VALUES (419, 'SL Benfica', 32);
INSERT INTO teams (id, name, league_id) VALUES (420, 'Santa Clara', 32);
INSERT INTO teams (id, name, league_id) VALUES (421, 'Sporting CP', 32);
INSERT INTO teams (id, name, league_id) VALUES (422, 'Vitória SC', 32);
INSERT INTO teams (id, name, league_id) VALUES (423, 'SL Benfica', 33);
INSERT INTO teams (id, name, league_id) VALUES (424, 'AJ Auxerre', 34);
INSERT INTO teams (id, name, league_id) VALUES (425, 'AS Monaco', 34);
INSERT INTO teams (id, name, league_id) VALUES (426, 'AS Saint-Étienne', 34);
INSERT INTO teams (id, name, league_id) VALUES (427, 'Angers SCO', 34);
INSERT INTO teams (id, name, league_id) VALUES (428, 'FC Nantes', 34);
INSERT INTO teams (id, name, league_id) VALUES (429, 'Havre AC', 34);
INSERT INTO teams (id, name, league_id) VALUES (430, 'LOSC Lille', 34);
INSERT INTO teams (id, name, league_id) VALUES (431, 'Montpellier', 34);
INSERT INTO teams (id, name, league_id) VALUES (432, 'OGC Nice', 34);
INSERT INTO teams (id, name, league_id) VALUES (433, 'OL', 34);
INSERT INTO teams (id, name, league_id) VALUES (434, 'OM', 34);
INSERT INTO teams (id, name, league_id) VALUES (435, 'Paris SG', 34);
INSERT INTO teams (id, name, league_id) VALUES (436, 'RC Lens', 34);
INSERT INTO teams (id, name, league_id) VALUES (437, 'Stade Brestois 29', 34);
INSERT INTO teams (id, name, league_id) VALUES (438, 'Stade Rennais FC', 34);
INSERT INTO teams (id, name, league_id) VALUES (439, 'Stade de Reims', 34);
INSERT INTO teams (id, name, league_id) VALUES (440, 'Strasbourg', 34);
INSERT INTO teams (id, name, league_id) VALUES (441, 'Toulouse FC', 34);
INSERT INTO teams (id, name, league_id) VALUES (442, 'AC Ajaccio', 35);
INSERT INTO teams (id, name, league_id) VALUES (443, 'Amiens SC', 35);
INSERT INTO teams (id, name, league_id) VALUES (444, 'Clermont Foot 63', 35);
INSERT INTO teams (id, name, league_id) VALUES (445, 'ESTAC Troyes', 35);
INSERT INTO teams (id, name, league_id) VALUES (446, 'En Avant Guingamp', 35);
INSERT INTO teams (id, name, league_id) VALUES (447, 'FC Annecy', 35);
INSERT INTO teams (id, name, league_id) VALUES (448, 'FC Lorient', 35);
INSERT INTO teams (id, name, league_id) VALUES (449, 'FC Martigues', 35);
INSERT INTO teams (id, name, league_id) VALUES (450, 'FC Metz', 35);
INSERT INTO teams (id, name, league_id) VALUES (451, 'Grenoble Foot 38', 35);
INSERT INTO teams (id, name, league_id) VALUES (452, 'Laval MFC', 35);
INSERT INTO teams (id, name, league_id) VALUES (453, 'Paris FC', 35);
INSERT INTO teams (id, name, league_id) VALUES (454, 'Pau FC', 35);
INSERT INTO teams (id, name, league_id) VALUES (455, 'Red Star FC', 35);
INSERT INTO teams (id, name, league_id) VALUES (456, 'Rodez AF', 35);
INSERT INTO teams (id, name, league_id) VALUES (457, 'SC Bastia', 35);
INSERT INTO teams (id, name, league_id) VALUES (458, 'SM Caen', 35);
INSERT INTO teams (id, name, league_id) VALUES (459, 'USL Dunkerque', 35);
INSERT INTO teams (id, name, league_id) VALUES (460, 'Atlanta United', 36);
INSERT INTO teams (id, name, league_id) VALUES (461, 'Austin FC', 36);
INSERT INTO teams (id, name, league_id) VALUES (462, 'CF Montréal', 36);
INSERT INTO teams (id, name, league_id) VALUES (463, 'Charlotte FC', 36);
INSERT INTO teams (id, name, league_id) VALUES (464, 'Chicago Fire FC', 36);
INSERT INTO teams (id, name, league_id) VALUES (465, 'Colorado Rapids', 36);
INSERT INTO teams (id, name, league_id) VALUES (466, 'Columbus Crew', 36);
INSERT INTO teams (id, name, league_id) VALUES (467, 'D.C. United', 36);
INSERT INTO teams (id, name, league_id) VALUES (468, 'FC Cincinnati', 36);
INSERT INTO teams (id, name, league_id) VALUES (469, 'FC Dallas', 36);
INSERT INTO teams (id, name, league_id) VALUES (470, 'Houston Dynamo', 36);
INSERT INTO teams (id, name, league_id) VALUES (471, 'Inter Miami CF', 36);
INSERT INTO teams (id, name, league_id) VALUES (472, 'LA Galaxy', 36);
INSERT INTO teams (id, name, league_id) VALUES (473, 'LAFC', 36);
INSERT INTO teams (id, name, league_id) VALUES (474, 'Minnesota United', 36);
INSERT INTO teams (id, name, league_id) VALUES (475, 'Nashville SC', 36);
INSERT INTO teams (id, name, league_id) VALUES (476, 'New England', 36);
INSERT INTO teams (id, name, league_id) VALUES (477, 'New York City FC', 36);
INSERT INTO teams (id, name, league_id) VALUES (478, 'Orlando City', 36);
INSERT INTO teams (id, name, league_id) VALUES (479, 'Philadelphia', 36);
INSERT INTO teams (id, name, league_id) VALUES (480, 'Portland Timbers', 36);
INSERT INTO teams (id, name, league_id) VALUES (481, 'Real Salt Lake', 36);
INSERT INTO teams (id, name, league_id) VALUES (482, 'Red Bulls', 36);
INSERT INTO teams (id, name, league_id) VALUES (483, 'SJ Earthquakes', 36);
INSERT INTO teams (id, name, league_id) VALUES (484, 'Sounders FC', 36);
INSERT INTO teams (id, name, league_id) VALUES (485, 'Sporting KC', 36);
INSERT INTO teams (id, name, league_id) VALUES (486, 'St. Louis CITY SC', 36);
INSERT INTO teams (id, name, league_id) VALUES (487, 'Toronto FC', 36);
INSERT INTO teams (id, name, league_id) VALUES (488, 'Whitecaps FC', 36);
INSERT INTO teams (id, name, league_id) VALUES (489, 'Ferencvárosi TC', 37);
INSERT INTO teams (id, name, league_id) VALUES (490, 'Angel City FC', 38);
INSERT INTO teams (id, name, league_id) VALUES (491, 'Bay FC', 38);
INSERT INTO teams (id, name, league_id) VALUES (492, 'Chicago Red Stars', 38);
INSERT INTO teams (id, name, league_id) VALUES (493, 'Houston Dash', 38);
INSERT INTO teams (id, name, league_id) VALUES (494, 'KC Current', 38);
INSERT INTO teams (id, name, league_id) VALUES (495, 'NC Courage', 38);
INSERT INTO teams (id, name, league_id) VALUES (496, 'NJ/NY Gotham', 38);
INSERT INTO teams (id, name, league_id) VALUES (497, 'Orlando Pride', 38);
INSERT INTO teams (id, name, league_id) VALUES (498, 'Portland Thorns', 38);
INSERT INTO teams (id, name, league_id) VALUES (499, 'Rac. Louisville', 38);
INSERT INTO teams (id, name, league_id) VALUES (500, 'San Diego Wave', 38);
INSERT INTO teams (id, name, league_id) VALUES (501, 'Seattle Reign', 38);
INSERT INTO teams (id, name, league_id) VALUES (502, 'Utah Royals FC', 38);
INSERT INTO teams (id, name, league_id) VALUES (503, 'Washington Spirit', 38);
INSERT INTO teams (id, name, league_id) VALUES (504, 'Ajax', 39);
INSERT INTO teams (id, name, league_id) VALUES (505, 'Cracovia', 40);
INSERT INTO teams (id, name, league_id) VALUES (506, 'GKS Katowice', 40);
INSERT INTO teams (id, name, league_id) VALUES (507, 'Górnik Zabrze', 40);
INSERT INTO teams (id, name, league_id) VALUES (508, 'Jagiellonia', 40);
INSERT INTO teams (id, name, league_id) VALUES (509, 'Korona Kielce', 40);
INSERT INTO teams (id, name, league_id) VALUES (510, 'Lech Poznań', 40);
INSERT INTO teams (id, name, league_id) VALUES (511, 'Lechia Gdańsk', 40);
INSERT INTO teams (id, name, league_id) VALUES (512, 'Legia Warszawa', 40);
INSERT INTO teams (id, name, league_id) VALUES (513, 'Motor Lublin', 40);
INSERT INTO teams (id, name, league_id) VALUES (514, 'Piast Gliwice', 40);
INSERT INTO teams (id, name, league_id) VALUES (515, 'Pogoń Szczecin', 40);
INSERT INTO teams (id, name, league_id) VALUES (516, 'Puszcza', 40);
INSERT INTO teams (id, name, league_id) VALUES (517, 'Radomiak Radom', 40);
INSERT INTO teams (id, name, league_id) VALUES (518, 'Raków', 40);
INSERT INTO teams (id, name, league_id) VALUES (519, 'Stal Mielec', 40);
INSERT INTO teams (id, name, league_id) VALUES (520, 'Widzew Łódź', 40);
INSERT INTO teams (id, name, league_id) VALUES (521, 'Zagłębie Lubin', 40);
INSERT INTO teams (id, name, league_id) VALUES (522, 'Śląsk Wrocław', 40);
INSERT INTO teams (id, name, league_id) VALUES (523, 'AFC Bournemouth', 41);
INSERT INTO teams (id, name, league_id) VALUES (524, 'Arsenal', 41);
INSERT INTO teams (id, name, league_id) VALUES (525, 'Aston Villa', 41);
INSERT INTO teams (id, name, league_id) VALUES (526, 'Brentford', 41);
INSERT INTO teams (id, name, league_id) VALUES (527, 'Brighton', 41);
INSERT INTO teams (id, name, league_id) VALUES (528, 'Chelsea', 41);
INSERT INTO teams (id, name, league_id) VALUES (529, 'Crystal Palace', 41);
INSERT INTO teams (id, name, league_id) VALUES (530, 'Everton', 41);
INSERT INTO teams (id, name, league_id) VALUES (531, 'Fulham', 41);
INSERT INTO teams (id, name, league_id) VALUES (532, 'Ipswich', 41);
INSERT INTO teams (id, name, league_id) VALUES (533, 'Leicester City', 41);
INSERT INTO teams (id, name, league_id) VALUES (534, 'Liverpool', 41);
INSERT INTO teams (id, name, league_id) VALUES (535, 'Man Utd', 41);
INSERT INTO teams (id, name, league_id) VALUES (536, 'Manchester City', 41);
INSERT INTO teams (id, name, league_id) VALUES (537, 'Newcastle Utd', 41);
INSERT INTO teams (id, name, league_id) VALUES (538, 'Nott''m Forest', 41);
INSERT INTO teams (id, name, league_id) VALUES (539, 'Southampton', 41);
INSERT INTO teams (id, name, league_id) VALUES (540, 'Spurs', 41);
INSERT INTO teams (id, name, league_id) VALUES (541, 'West Ham', 41);
INSERT INTO teams (id, name, league_id) VALUES (542, 'Wolves', 41);
INSERT INTO teams (id, name, league_id) VALUES (543, 'Atlético Tucumán', 42);
INSERT INTO teams (id, name, league_id) VALUES (544, 'Banfield', 42);
INSERT INTO teams (id, name, league_id) VALUES (545, 'Barracas Central', 42);
INSERT INTO teams (id, name, league_id) VALUES (546, 'Central Córdoba', 42);
INSERT INTO teams (id, name, league_id) VALUES (547, 'Dep. Riestra', 42);
INSERT INTO teams (id, name, league_id) VALUES (548, 'Gimnasia', 42);
INSERT INTO teams (id, name, league_id) VALUES (549, 'Godoy Cruz', 42);
INSERT INTO teams (id, name, league_id) VALUES (550, 'Huracán', 42);
INSERT INTO teams (id, name, league_id) VALUES (551, 'Ind. Rivadavia', 42);
INSERT INTO teams (id, name, league_id) VALUES (552, 'Independiente', 42);
INSERT INTO teams (id, name, league_id) VALUES (553, 'Instituto', 42);
INSERT INTO teams (id, name, league_id) VALUES (554, 'Newell''s', 42);
INSERT INTO teams (id, name, league_id) VALUES (555, 'Platense', 42);
INSERT INTO teams (id, name, league_id) VALUES (556, 'Sarmiento', 42);
INSERT INTO teams (id, name, league_id) VALUES (557, 'Tigre', 42);
INSERT INTO teams (id, name, league_id) VALUES (558, 'Unión', 42);
INSERT INTO teams (id, name, league_id) VALUES (559, 'Vélez Sarsfield', 42);
INSERT INTO teams (id, name, league_id) VALUES (560, 'Al Ahli', 43);
INSERT INTO teams (id, name, league_id) VALUES (561, 'Al Fateh', 43);
INSERT INTO teams (id, name, league_id) VALUES (562, 'Al Fayha', 43);
INSERT INTO teams (id, name, league_id) VALUES (563, 'Al Hilal', 43);
INSERT INTO teams (id, name, league_id) VALUES (564, 'Al Ittihad', 43);
INSERT INTO teams (id, name, league_id) VALUES (565, 'Al Khaleej', 43);
INSERT INTO teams (id, name, league_id) VALUES (566, 'Al Kholood', 43);
INSERT INTO teams (id, name, league_id) VALUES (567, 'Al Nassr', 43);
INSERT INTO teams (id, name, league_id) VALUES (568, 'Al Okhdood', 43);
INSERT INTO teams (id, name, league_id) VALUES (569, 'Al Orobah', 43);
INSERT INTO teams (id, name, league_id) VALUES (570, 'Al Qadisiyah', 43);
INSERT INTO teams (id, name, league_id) VALUES (571, 'Al Raed', 43);
INSERT INTO teams (id, name, league_id) VALUES (572, 'Al Riyadh', 43);
INSERT INTO teams (id, name, league_id) VALUES (573, 'Al Shabab', 43);
INSERT INTO teams (id, name, league_id) VALUES (574, 'Al Taawoun', 43);
INSERT INTO teams (id, name, league_id) VALUES (575, 'Al Wehda', 43);
INSERT INTO teams (id, name, league_id) VALUES (576, 'Damac FC', 43);
INSERT INTO teams (id, name, league_id) VALUES (577, 'Ettifaq FC', 43);
INSERT INTO teams (id, name, league_id) VALUES (578, 'Bohemians', 44);
INSERT INTO teams (id, name, league_id) VALUES (579, 'Derry City', 44);
INSERT INTO teams (id, name, league_id) VALUES (580, 'Drogheda United', 44);
INSERT INTO teams (id, name, league_id) VALUES (581, 'Dundalk', 44);
INSERT INTO teams (id, name, league_id) VALUES (582, 'Galway United', 44);
INSERT INTO teams (id, name, league_id) VALUES (583, 'Shamrock Rovers', 44);
INSERT INTO teams (id, name, league_id) VALUES (584, 'Shelbourne', 44);
INSERT INTO teams (id, name, league_id) VALUES (585, 'Sligo Rovers', 44);
INSERT INTO teams (id, name, league_id) VALUES (586, 'St. Pats', 44);
INSERT INTO teams (id, name, league_id) VALUES (587, 'Waterford', 44);
INSERT INTO teams (id, name, league_id) VALUES (588, 'CFR 1907 Cluj', 45);
INSERT INTO teams (id, name, league_id) VALUES (589, 'FC Botoșani', 45);
INSERT INTO teams (id, name, league_id) VALUES (590, 'FC Dinamo 1948', 45);
INSERT INTO teams (id, name, league_id) VALUES (591, 'FC Gloria Buzău', 45);
INSERT INTO teams (id, name, league_id) VALUES (592, 'FC Hermannstadt', 45);
INSERT INTO teams (id, name, league_id) VALUES (593, 'FC Petrolul', 45);
INSERT INTO teams (id, name, league_id) VALUES (594, 'FC Rapid 1923', 45);
INSERT INTO teams (id, name, league_id) VALUES (595, 'FC Univ. Cluj', 45);
INSERT INTO teams (id, name, league_id) VALUES (596, 'FCSB', 45);
INSERT INTO teams (id, name, league_id) VALUES (597, 'Farul Constanța', 45);
INSERT INTO teams (id, name, league_id) VALUES (598, 'Politehnica Iași', 45);
INSERT INTO teams (id, name, league_id) VALUES (599, 'SC Oțelul Galați', 45);
INSERT INTO teams (id, name, league_id) VALUES (600, 'Sepsi OSK', 45);
INSERT INTO teams (id, name, league_id) VALUES (601, 'UTA Arad', 45);
INSERT INTO teams (id, name, league_id) VALUES (602, 'Unirea Slobozia', 45);
INSERT INTO teams (id, name, league_id) VALUES (603, 'Univ. Craiova', 45);
INSERT INTO teams (id, name, league_id) VALUES (604, 'FC Zürich', 46);
INSERT INTO teams (id, name, league_id) VALUES (605, 'Aberdeen', 47);
INSERT INTO teams (id, name, league_id) VALUES (606, 'Celtic', 47);
INSERT INTO teams (id, name, league_id) VALUES (607, 'Dundee FC', 47);
INSERT INTO teams (id, name, league_id) VALUES (608, 'Dundee United', 47);
INSERT INTO teams (id, name, league_id) VALUES (609, 'Hearts', 47);
INSERT INTO teams (id, name, league_id) VALUES (610, 'Hibernian', 47);
INSERT INTO teams (id, name, league_id) VALUES (611, 'Kilmarnock', 47);
INSERT INTO teams (id, name, league_id) VALUES (612, 'Motherwell', 47);
INSERT INTO teams (id, name, league_id) VALUES (613, 'Rangers', 47);
INSERT INTO teams (id, name, league_id) VALUES (614, 'Ross County', 47);
INSERT INTO teams (id, name, league_id) VALUES (615, 'St. Johnstone', 47);
INSERT INTO teams (id, name, league_id) VALUES (616, 'St. Mirren', 47);
INSERT INTO teams (id, name, league_id) VALUES (617, 'Glasgow City FC', 48);
INSERT INTO teams (id, name, league_id) VALUES (618, 'AS Roma', 49);
INSERT INTO teams (id, name, league_id) VALUES (619, 'Bergamo Calcio', 49);
INSERT INTO teams (id, name, league_id) VALUES (620, 'Bologna', 49);
INSERT INTO teams (id, name, league_id) VALUES (621, 'Cagliari', 49);
INSERT INTO teams (id, name, league_id) VALUES (622, 'Como', 49);
INSERT INTO teams (id, name, league_id) VALUES (623, 'Empoli', 49);
INSERT INTO teams (id, name, league_id) VALUES (624, 'Fiorentina', 49);
INSERT INTO teams (id, name, league_id) VALUES (625, 'Genoa', 49);
INSERT INTO teams (id, name, league_id) VALUES (626, 'Hellas Verona', 49);
INSERT INTO teams (id, name, league_id) VALUES (627, 'Juventus', 49);
INSERT INTO teams (id, name, league_id) VALUES (628, 'Latium', 49);
INSERT INTO teams (id, name, league_id) VALUES (629, 'Lecce', 49);
INSERT INTO teams (id, name, league_id) VALUES (630, 'Lombardia FC', 49);
INSERT INTO teams (id, name, league_id) VALUES (631, 'Milano FC', 49);
INSERT INTO teams (id, name, league_id) VALUES (632, 'Monza', 49);
INSERT INTO teams (id, name, league_id) VALUES (633, 'Parma', 49);
INSERT INTO teams (id, name, league_id) VALUES (634, 'SSC Napoli', 49);
INSERT INTO teams (id, name, league_id) VALUES (635, 'Torino', 49);
INSERT INTO teams (id, name, league_id) VALUES (636, 'Udinese', 49);
INSERT INTO teams (id, name, league_id) VALUES (637, 'Venezia', 49);
INSERT INTO teams (id, name, league_id) VALUES (638, 'Bari', 50);
INSERT INTO teams (id, name, league_id) VALUES (639, 'Brescia', 50);
INSERT INTO teams (id, name, league_id) VALUES (640, 'Carrarese Calcio', 50);
INSERT INTO teams (id, name, league_id) VALUES (641, 'Catanzaro', 50);
INSERT INTO teams (id, name, league_id) VALUES (642, 'Cesena', 50);
INSERT INTO teams (id, name, league_id) VALUES (643, 'Cittadella', 50);
INSERT INTO teams (id, name, league_id) VALUES (644, 'Cosenza', 50);
INSERT INTO teams (id, name, league_id) VALUES (645, 'Cremonese', 50);
INSERT INTO teams (id, name, league_id) VALUES (646, 'Frosinone', 50);
INSERT INTO teams (id, name, league_id) VALUES (647, 'Mantova', 50);
INSERT INTO teams (id, name, league_id) VALUES (648, 'Modena', 50);
INSERT INTO teams (id, name, league_id) VALUES (649, 'Palermo', 50);
INSERT INTO teams (id, name, league_id) VALUES (650, 'Pisa', 50);
INSERT INTO teams (id, name, league_id) VALUES (651, 'Reggiana', 50);
INSERT INTO teams (id, name, league_id) VALUES (652, 'SS Juve Stabia', 50);
INSERT INTO teams (id, name, league_id) VALUES (653, 'Salernitana', 50);
INSERT INTO teams (id, name, league_id) VALUES (654, 'Sampdoria', 50);
INSERT INTO teams (id, name, league_id) VALUES (655, 'Sassuolo', 50);
INSERT INTO teams (id, name, league_id) VALUES (656, 'Spezia', 50);
INSERT INTO teams (id, name, league_id) VALUES (657, 'Südtirol', 50);
INSERT INTO teams (id, name, league_id) VALUES (658, 'ADT', 51);
INSERT INTO teams (id, name, league_id) VALUES (659, 'Alianza FC', 51);
INSERT INTO teams (id, name, league_id) VALUES (660, 'Always Ready', 51);
INSERT INTO teams (id, name, league_id) VALUES (661, 'América de Cali', 51);
INSERT INTO teams (id, name, league_id) VALUES (662, 'Argentinos Jrs.', 51);
INSERT INTO teams (id, name, league_id) VALUES (663, 'Belgrano', 51);
INSERT INTO teams (id, name, league_id) VALUES (664, 'Boca Juniors', 51);
INSERT INTO teams (id, name, league_id) VALUES (665, 'Carabobo FC', 51);
INSERT INTO teams (id, name, league_id) VALUES (666, 'Cerro Largo', 51);
INSERT INTO teams (id, name, league_id) VALUES (667, 'Club Nacional', 51);
INSERT INTO teams (id, name, league_id) VALUES (668, 'Coquimbo Unido', 51);
INSERT INTO teams (id, name, league_id) VALUES (669, 'Danubio', 51);
INSERT INTO teams (id, name, league_id) VALUES (670, 'Defensa', 51);
INSERT INTO teams (id, name, league_id) VALUES (671, 'Delfín SC', 51);
INSERT INTO teams (id, name, league_id) VALUES (672, 'Dep. Cuenca', 51);
INSERT INTO teams (id, name, league_id) VALUES (673, 'Dep. Garcilaso', 51);
INSERT INTO teams (id, name, league_id) VALUES (674, 'Dep. La Guaira', 51);
INSERT INTO teams (id, name, league_id) VALUES (675, 'Deportes Tolima', 51);
INSERT INTO teams (id, name, league_id) VALUES (676, 'Everton', 51);
INSERT INTO teams (id, name, league_id) VALUES (677, 'Guaraní', 51);
INSERT INTO teams (id, name, league_id) VALUES (678, 'Indep. Medellín', 51);
INSERT INTO teams (id, name, league_id) VALUES (679, 'Lanús', 51);
INSERT INTO teams (id, name, league_id) VALUES (680, 'Metropolitanos', 51);
INSERT INTO teams (id, name, league_id) VALUES (681, 'Nacional Potosí', 51);
INSERT INTO teams (id, name, league_id) VALUES (682, 'Olimpia', 51);
INSERT INTO teams (id, name, league_id) VALUES (683, 'Racing Club', 51);
INSERT INTO teams (id, name, league_id) VALUES (684, 'Rayo Zuliano', 51);
INSERT INTO teams (id, name, league_id) VALUES (685, 'Real Tomayapo', 51);
INSERT INTO teams (id, name, league_id) VALUES (686, 'S. Ameliano', 51);
INSERT INTO teams (id, name, league_id) VALUES (687, 'S. Trinidense', 51);
INSERT INTO teams (id, name, league_id) VALUES (688, 'Sport Huancayo', 51);
INSERT INTO teams (id, name, league_id) VALUES (689, 'Sportivo Luqueño', 51);
INSERT INTO teams (id, name, league_id) VALUES (690, 'Técnico U.', 51);
INSERT INTO teams (id, name, league_id) VALUES (691, 'U. Católica', 51);
INSERT INTO teams (id, name, league_id) VALUES (692, 'UCV', 51);
INSERT INTO teams (id, name, league_id) VALUES (693, 'Uni. Católica', 51);
INSERT INTO teams (id, name, league_id) VALUES (694, 'Universitario', 51);
INSERT INTO teams (id, name, league_id) VALUES (695, 'Unión La Calera', 51);
INSERT INTO teams (id, name, league_id) VALUES (696, 'Wanderers', 51);
INSERT INTO teams (id, name, league_id) VALUES (697, 'Wilstermann', 51);
INSERT INTO teams (id, name, league_id) VALUES (698, 'FC Rosengård', 52);
INSERT INTO teams (id, name, league_id) VALUES (699, 'Adana Demirspor', 53);
INSERT INTO teams (id, name, league_id) VALUES (700, 'Alanyaspor', 53);
INSERT INTO teams (id, name, league_id) VALUES (701, 'Antalyaspor', 53);
INSERT INTO teams (id, name, league_id) VALUES (702, 'Başakşehir', 53);
INSERT INTO teams (id, name, league_id) VALUES (703, 'Beşiktaş', 53);
INSERT INTO teams (id, name, league_id) VALUES (704, 'Bodrum FK', 53);
INSERT INTO teams (id, name, league_id) VALUES (705, 'Eyüpspor', 53);
INSERT INTO teams (id, name, league_id) VALUES (706, 'Fenerbahçe', 53);
INSERT INTO teams (id, name, league_id) VALUES (707, 'Galatasaray', 53);
INSERT INTO teams (id, name, league_id) VALUES (708, 'Gaziantep', 53);
INSERT INTO teams (id, name, league_id) VALUES (709, 'Göztepe', 53);
INSERT INTO teams (id, name, league_id) VALUES (710, 'Hatayspor', 53);
INSERT INTO teams (id, name, league_id) VALUES (711, 'Kasımpaşa', 53);
INSERT INTO teams (id, name, league_id) VALUES (712, 'Kayserispor', 53);
INSERT INTO teams (id, name, league_id) VALUES (713, 'Konyaspor', 53);
INSERT INTO teams (id, name, league_id) VALUES (714, 'Samsunspor', 53);
INSERT INTO teams (id, name, league_id) VALUES (715, 'Sivasspor', 53);
INSERT INTO teams (id, name, league_id) VALUES (716, 'Trabzonspor', 53);
INSERT INTO teams (id, name, league_id) VALUES (717, 'Çaykur Rizespor', 53);
INSERT INTO teams (id, name, league_id) VALUES (718, 'Dynamo Kyiv', 54);
INSERT INTO teams (id, name, league_id) VALUES (719, 'Shakhtar Donetsk', 54);
INSERT INTO teams (id, name, league_id) VALUES (720, 'Al Ain FC', 55);
INSERT INTO teams (id, name, league_id) VALUES (721, 'Austria Klagenfurt', 56);
INSERT INTO teams (id, name, league_id) VALUES (722, 'Blau-Weiss Linz', 56);
INSERT INTO teams (id, name, league_id) VALUES (723, 'FK Austria Wien', 56);
INSERT INTO teams (id, name, league_id) VALUES (724, 'Grazer AK', 56);
INSERT INTO teams (id, name, league_id) VALUES (725, 'LASK', 56);
INSERT INTO teams (id, name, league_id) VALUES (726, 'RB Salzburg', 56);
INSERT INTO teams (id, name, league_id) VALUES (727, 'SCR Altach', 56);
INSERT INTO teams (id, name, league_id) VALUES (728, 'SK Rapid', 56);
INSERT INTO teams (id, name, league_id) VALUES (729, 'SK Sturm Graz', 56);
INSERT INTO teams (id, name, league_id) VALUES (730, 'TSV Hartberg', 56);
INSERT INTO teams (id, name, league_id) VALUES (731, 'WSG Tirol', 56);
INSERT INTO teams (id, name, league_id) VALUES (732, 'Wolfsberger AC', 56);
INSERT INTO teams (id, name, league_id) VALUES (733, 'Slavia Praha', 57);
INSERT INTO teams (id, name, league_id) VALUES (734, 'Sparta Praha', 57);
INSERT INTO teams (id, name, league_id) VALUES (735, 'Viktoria Plzeň', 57);

SELECT setval(pg_get_serial_sequence('teams', 'id'), 736, false);

-- migrate:down 

DELETE FROM teams;

SELECT setval(pg_get_serial_sequence('teams', 'id'), 1, false);